In [2]:
import numpy as np
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [3]:
import numpy as np
arr = np.array([1,2.,3.])
arr

array([1., 2., 3.])

In [6]:
import numpy as np
arr =  np.array([[1,2.,3.],[4.,5.,7]])
arr

array([[1., 2., 3.],
       [4., 5., 7.]])

In [8]:
import numpy as np
arr = np.array([1,2.,3.],ndmin =2)
arr

array([[1., 2., 3.]])

In [9]:
import numpy as np
arr = np.array([12.,45,3],dtype =complex)
arr

array([12.+0.j, 45.+0.j,  3.+0.j])

In [28]:
import numpy as np
arr= np.array(np.mat('1 2;3 4'))
(arr)
arr= np.array(np.mat('1 3;3 4'),subok=True)
arr

AttributeError: `np.mat` was removed in the NumPy 2.0 release. Use `np.asmatrix` instead.

In [30]:
import array as arr
a = arr.array('i',[2,4,5,6])
print("1st element", a[0])
print("2nd element", a[1])
print("3rd element", a[2])
print("4th element", a[3])
print("Last element", a[-1])
print("last 2nd element", a[-2])
print("last 3rd element", a[-3])
print("last 4th element", a[-4])
print(a[0],a[1],a[2],a[3],a[-1],a[-2],a[-3],a[-4])

1st element 2
2nd element 4
3rd element 5
4th element 6
Last element 6
last 2nd element 5
last 3rd element 4
last 4th element 2
2 4 5 6 6 5 4 2


In [31]:
import array as arr
number = arr.array('i',[1,2,3,3,4])
del number[2]
print(number)

array('i', [1, 2, 3, 4])


In [1]:
import array as arr
a = arr.array('d',[1.1,2.1,3.1,2.6,7.8])
b = arr.array('d',[3.7,8.6])
c = arr.array('d')
c = a+b
print("Array C =" ,c)

Array C = array('d', [1.1, 2.1, 3.1, 2.6, 7.8, 3.7, 8.6])


In [3]:
import array as arr
x = arr.array('i', [4,7,29,22])
print("First element", x[0])
print("Second element", x[1])
print("last element", x[-1])


First element 4
Second element 7
last element 22


In [6]:
places = ['Delhi','Tokyo','London','Washington DC']
with open ("newfile.txt",'w') as filehandle:
    
    for listitem in places:
        filehandle.write(f'{listitem}/n')
    capitals =[]