# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

In [1]:
class Employee:
    id = 10
    name = "Jhon"
    def display(self):
        print("ID : %d\n Name: %s"%(self.id,self.name))
emp = Employee()
emp.display()

ID : 10
 Name: Jhon


In [2]:
def add (x,y):
    return x+y
print(add.__doc__)

None


In [6]:
class student:
    def __init__(self):
        print("This is non parametrized constructor")
    def show(self,name):
        print("Hello",name)
student= student()
student.show("Jhon")

This is non parametrized constructor
Hello Jhon


In [9]:
class Animal:
    def speak(self):
        print("Animal Speaking")
class dog(Animal):
    def bark(self):
        print("Dog barking")
d = dog()
d.bark()
d.speak()

Dog barking
Animal Speaking


In [20]:
from abc import ABC,abstractmethod
class Car(ABC):
    def mileage(self):
        pass
class Tesla(Car):
    def mileage(self):
        print("The mileage is 30kmph")
class Suzuki(Car):
    def mileage(self):
        print("The mileage is 25kmph")
class Duster(Car):
    def mileage(self):
        print("The mileage is 24kmph ")
class Renault(Car):
    def mileage(self):
        print("The mileage is 37kmph ")
t=Tesla()
t.mileage()
r=Renault()
r.mileage()

s=Suzuki()
s.mileage()
d=Duster()
d.mileage()


The mileage is 30kmph
The mileage is 37kmph 
The mileage is 25kmph
The mileage is 24kmph 


In [21]:
class Birds:
    def intro1(self):
        print("There are multiple types of birds in the world.")
    def flight1(self):
        print("Many of these birds can fly but some cannot.")
class sparrow1(Birds):
    def flight1(self):
        print("Sparrows are the bird which can fly.")
class ostrich1(Birds):
    def flight1(self):
        print("Ostriches are the birds which cannot fly.")
obj_birds=Birds()
obj_spr1=sparrow1()
obj_ost1=ostrich1()
obj_birds.intro1()
obj_birds.flight1()
obj_spr1.intro1()
obj_spr1.flight1()
obj_ost1.intro1()
obj_ost1.flight1()

There are multiple types of birds in the world.
Many of these birds can fly but some cannot.
There are multiple types of birds in the world.
Sparrows are the bird which can fly.
There are multiple types of birds in the world.
Ostriches are the birds which cannot fly.


In [1]:
a = 3
print(a/0)


ZeroDivisionError: division by zero

In [2]:
try:
    array = [1,2,2,3,4]
    for i in range (0,5):
	        print ("The element in",i,"index is:",array[i])
except:
    print ("Tried to access an out of bound index-check it")

The element in 0 index is: 1
The element in 1 index is: 2
The element in 2 index is: 2
The element in 3 index is: 3
The element in 4 index is: 4


In [4]:
try:
    array = [2,3,5,6]
    print(array)
    for i in range(0,5):
        print("The element in" , i , "index is:",array[i])
        for i in reversed(range(-1,3)):
            print(array[0]/0)
except IndexError:  (
    print("Tried to access an out of bound index-check it"))
except ZeroDivisionError:
    print("Oops! Division by zero")



[2, 3, 5, 6]
The element in 0 index is: 2
Oops! Division by zero


In [6]:
a = ["Python", "Exceptions", "try and except"]
try:
    for i in range( 4 ):
        print( "The index and element from the array is", i, a[i] )
except:
    print ("Index out of range")

The index and element from the array is 0 Python
The index and element from the array is 1 Exceptions
The index and element from the array is 2 try and except
Index out of range


In [7]:
num = [3, 4, 5, 7]
if len(num) > 3:
    raise Exception( f"Length of the given list must be less than or equal to 3 but is {len(num)}" )


Exception: Length of the given list must be less than or equal to 3 but is 4

In [5]:
try:
    div = 4 // 0
    print( div )
except ZeroDivisionError:
    print( "Atepting to divide by zero" )
finally:
    print( 'This is code of finally clause' )

Atepting to divide by zero
This is code of finally clause


In [8]:
import numpy as np
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [10]:
import numpy as np
arr = np.array([[1,2.,3.],[4,5.,6.]])
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]]


In [11]:
import numpy as np
arr = np.array([1,2.,3.],ndmin=2)
arr

array([[1., 2., 3.]])

In [12]:
import numpy as np
arr = np.array([1,2.,3.],dtype=complex)
arr

array([1.+0.j, 2.+0.j, 3.+0.j])

In [1]:
import threading
import time
def cal_square(num):
    print("Calculating square of number")
    for n in num:
        time.sleep(0.3)
        print("square is ",n*n)
arr = [4,5,6,7,8]
t1=time.time()
cal_square(arr)
print("total time taken by threads is ",time.time()-t1)

Calculating square of number
square is  16
square is  25
square is  36
square is  49
square is  64
total time taken by threads is  1.5130228996276855
